library(openxlsx)
library(dplyr)
library(magrittr)
library(tidyr)

#IMF Financial Access Survey
fas<- read.xlsx('Data/ExternalDBs/FAS Data Refresh.xlsx', 
                startRow= 3)

#All the names and the Country codes are in every row in the hidden columns 1 and 2.
#this means we can delete 'Row.Labels" and the second "ISO.Code" column (column 3 and 4).
fas$Row.Labels <- NULL
fas[,3] <- NULL #Used the column number because it was named the same as another column

x<- c('Country.Name',
      'Country.Code',
      'Reporting.Year',
      'Commercial.banks.SME.borrowers',
      'Commercial.banks.SME.loan.accounts',
      'Commercial.banks.SME.Outstanding.Deposits',
      'Commercial.banks.SME.Outstanding.Loans',
      'Credit.unions.and.financial.cooperatives.household.borrowers',
      'Credit.unions.and.financial.cooperatives.household.depositors',
      'Credit.unions.and.financial.cooperatives.household.loan.accounts',
      'Credit.unions.and.financial.cooperatives.household.Outstanding.Deposits',
      'Credit.unions.and.financial.cooperatives.household.Outstanding.Loans',
      'Credit.unions.and.financial.cooperatives.in.3.largest.cities.Number.of.Branches',
      'Credit.unions.and.financial.cooperatives.SME.borrowers',
      'Credit.unions.and.financial.cooperatives.SME.depositors',
      'Credit.unions.and.financial.cooperatives.SME.loan.accounts',
      'Credit.unions.and.financial.cooperatives.SME.Outstanding.Deposits',
      'Credit.unions.and.financial.cooperatives.SME.Outstanding.Loans',
      'Deposit.taking.MFIs.household.borrowers',
      'Deposit.taking.MFIs.household.depositors',
      'Deposit.taking.MFIs.household.loan.accounts',
      'Deposit.taking.MFIs.household.Outstanding.Deposits',
      'Deposit.taking.MFIs.household.Outstanding.Loans',
      'Deposit.taking.MFIs.in.3.largest.cities.Number.of.Branches',
      'Deposit.taking.MFIs.SME.borrowers',
      'Deposit.taking.MFIs.SME.depositors',
      'Deposit.taking.MFIs.SME.loan.accounts',
      'Deposit.taking.MFIs.SME.Outstanding.Deposits',
      'Deposit.taking.MFIs.SME.Outstanding.Loans',
      'Insurance.corporations.Life.insurance.policies',
      'Insurance.Corporations.Life.insurance.policy.holders',
      'Insurance.corporations.Life.insurance.tech.reserves',
      'Insurance.corporations.Non.life.insurance.policies',
      'Insurance.Corporations.Non.life.insurance.policy.holders',
      'Insurance.corporations.Non.life.insurance.tech.reserves',
      'Non.deposit.taking.MFIs.funds.from.households',
      'Non.deposit.taking.MFIs.funds.from.SMEs',
      'Non.deposit.taking.MFIs.household.borrowers',
      'Non.deposit.taking.MFIs.household.loan.accounts',
      'Non.deposit.taking.MFIs.in.3.largest.cities.Number.of.Branches',
      'Non.deposit.taking.MFIs.loans.from.households',
      'Non.deposit.taking.MFIs.loans.from.SMEs',
      'Non.deposit.taking.MFIs.SME.borrowers',
      'Non.deposit.taking.MFIs.SME.loan.accounts',
      'Other.deposit.takers.in.3.largest.cities.Number.of.Branches',
      'Other.financial.intermediaries.funds.from.households',
      'Other.financial.intermediaries.funds.from.SMEs',
      'Other.financial.intermediaries.household.borrowers',
      'Other.financial.intermediaries.household.loan.accounts',
      'Other.financial.intermediaries.loans.from.households',
      'Other.financial.intermediaries.loans.from.SMEs',
      'Other.financial.intermediaries.SME.borrowers',
      'Other.financial.intermediaries.SME.loan.accounts',
      'Non.deposit.taking.MFIs.household.customers',
      'Non.deposit.taking.MFIs.SME.customers',
      'Other.financial.intermediaries.household.customers',
      'Other.financial.intermediaries.SME.customers',
      'Commercial.banks.household.borrowers',
      'Non.deposit.taking.MFIs.Number.of.Borrowers',
      'Non.deposit.taking.MFIs.Number.of.loan.accounts',
      'Non.deposit.taking.MFIs.Outstanding.Loans',
      'of.which.non.deposit.taking.MFIs',
      'Non.deposit.taking.MFIs.Number.of.Branches',
      'Other.financial.intermediaries.in.3.largest.cities.Number.of.Branches',
      'Other.OFIs.Number.of.Branches',
      'Commercial.banks.Number.of.Borrowers',
      'Commercial.banks.Number.of.Deposit.Accounts',
      'Commercial.banks.Number.of.loan.accounts',
      'Commercial.banks.household.loan.accounts',
      'Commercial.banks.household.Outstanding.Deposits',
      'Commercial.banks.household.Outstanding.Loans',
      'Commercial.banks.Outstanding.Deposits',
      'Commercial.banks.Outstanding.Loans',
      'Credit.unions.and.financial.cooperatives',
      'Credit.unions.and.financial.cooperatives.Number.of.Borrowers',
      'Credit.unions.and.financial.cooperatives.Number.of.Branches',
      'Credit.unions.and.financial.cooperatives.Number.of.Deposit.Accounts',
      'Credit.unions.and.financial.cooperatives.Number.of.Depositors',
      'Credit.unions.and.financial.cooperatives.Number.of.loan.accounts',
      'Credit.unions.and.financial.cooperatives.Outstanding.Deposits',
      'Credit.unions.and.financial.cooperatives.Outstanding.Loans',
      'Deposit.taking.MFIs.Number.of.Borrowers',
      'Deposit.taking.MFIs.Number.of.Branches',
      'Deposit.taking.MFIs.Number.of.Deposit.Accounts',
      'Deposit.taking.MFIs.Number.of.Depositors',
      'Deposit.taking.MFIs.Number.of.loan.accounts',
      'Deposit.taking.MFIs.Outstanding.Deposits',
      'Deposit.taking.MFIs.Outstanding.Loans',
      'Insurance.Corporations',
      'Insurance.corporations.Outstanding.Deposits',
      'Number.of.Automated.Teller.Machines',
      'Number.of.Automated.Teller.Machines.3.largest.cities',
      'Other.deposit.takers.Number.of.Branches',
      'Other.deposit.takers.Number.of.Deposit.Accounts',
      'Other.Depository.Corporations',
      'Other.Depository.Corporations.Number.of.Borrowers',
      'Other.Depository.Corporations.Number.of.Branches',
      'Other.Depository.Corporations.Number.of.Deposit.Accounts',
      'Other.Depository.Corporations.Number.of.Depositors',
      'Other.Depository.Corporations.Number.of.loan.accounts',
      'Other.Depository.Corporations.Outstanding.Deposits',
      'Other.Depository.Corporations.Outstanding.Loans',
      'Other.Financial.Corporations',
      'Other.financial.intermediaries.Number.of.Borrowers',
      'Other.financial.intermediaries.Number.of.Branches',
      'Other.financial.intermediaries.Number.of.loan.accounts',
      'Other.financial.intermediaries.Outstanding.Loans',
      'Outstanding.deposits.of.nonfinancial.corporations.and.households.IFS',
      'Outstanding.loans.of.nonfinancial.corporations.and.households.IFS',
      'SME.borrowers.from.commercial.banks.of.non.financial.corporation.borrowers.from.commercial.banks',
      'Credit.union.and.financial.cooperative.branches.per.100.000.adults',
      'Outstanding.loans.from.commercial.banks.percent.of.GDP',
      'Adult.Population',
      'Land.mass.of.country.in.Kilometers',
      'Outstanding.deposits.with.credit.unions.and.financial.cooperatives.percent.of.GDP',
      'Borrowers.from.credit.unions.and.financial.cooperatives.per.1000.adults',
      'Commercial.bank.branches.per.100.000.adults',
      'All.MFI.branches.per.1000.km2',
      'Depositors.with.commercial.banks.per.1000.adults',
      'ATMs.per.100.000.adults',
      'Borrowers.from.commercial.banks.per.1000.adults',
      'Outstanding.household.deposits.with.commercial.banks.percent.of.GDP',
      'Credit.union.and.financial.cooperative.branches.per.1000.km2',
      'Loan.accounts.with.commercial.banks.per.1000.adults',
      'Commercial.bank.branches.per.1000.km2',
      'ATMs.per.1000.km2',
      'Borrowers.from.all.MFIs.per.1000.adults',
      'Household.deposit.accounts.with.commercial.banks.per.1000.adults',
      'Outstanding.deposits.with.commercial.banks.percent.of.GDP',
      'Household.depositors.with.commercial.banks.per.1000.adults',
      'Outstanding.SME.loans.from.commercial.banks.percent.of.GDP.',
      'Household.loan.accounts.with.commercial.banks.per.1000.adults',
      'Outstanding.loans.from.credit.unions.and.financial.cooperatives.percent.of.GDP',
      'Outstanding.household.loans.from.commercial.banks.percent.of.GDP',
      'Deposit.accounts.with.commercial.banks.per.1000.adults',
      'Depositors.with.credit.unions.and.financial.cooperatives.per.1000.adults',
      'Outstanding.loans.from.all.MFIs.percent.of.GDP',
      'Outstanding.SME.deposits.with.commercial.banks.percent.of.GDP',
      'Deposit.customer.accounts.with.all.MFIs.per.1000.adults',
      'Loan.accounts.with.credit.unions.and.financial.cooperatives.per.1000.adults',
      'All.MFI.branches.per.100.000.adults',
      'Depositors.customers.with.all.MFIs.per.1000.adults',
      'Household.borrowers.from.commercial.banks.per.1000.adults',
      'Loan.accounts.with.all.MFIs.per.1000.adults',
      'Deposit.accounts.with.credit.unions.and.financial.cooperatives.per.1000.adults',
      'Other.Financial.Corporations.Acquired.Funds',
      'Deposit.taking.MFIs.SME.deposit.accounts',
      'Credit.unions.and.financial.cooperatives.SME.deposit.accounts',
      'Other.OFIs.Number.of.Customer.Accounts',
      'Other.financial.intermediaries.household.customer.accounts',
      'Deposit.taking.MFIs.household.deposit.accounts',
      'Commercial.banks.Number.of.Branches',
      'Other.Deposit.Takers.household.outstanding.loans',
      'Other.Deposit.Takers.household.outstanding.deposits',
      'Other.Deposit.Takers.Outstanding.Loans',
      'Other.Deposit.Takers.SME.Outstanding.Deposits',
      'Other.financial.intermediaries.Number.of.Customers',
      'Other.Deposit.Takers.Outstanding.Deposits',
      'Other.Financial.Corporations.Number.of.Customer.Accounts',
      'Other.financial.intermediaries',
      'Other.Deposit.Takers.Number.of.Borrowers',
      'Insurance.corporations.Number.of.policies',
      'Other.Deposit.Takers.Number.of.Depositors',
      'Commercial.banks.SME.depositors',
      'Commercial.banks.household.deposit.accounts',
      'Non.deposit.taking.MFIs.household.customer.accounts',
      'Other.Deposit.Takers',
      'Deposit.taking.microfinance.institutions',
      'Commercial.banks',
      'Other.Deposit.Takers.SME.outstanding.loans',
      'Other.financial.intermediaries.Acquired.Funds',
      'Commercial.banks.Number.of.Depositors',
      'Other.Deposit.Takers.SME.loan.accounts',
      'Credit.unions.and.financial.cooperatives.household.deposit.accounts',
      'Other.Deposit.Takers.SME.deposit.accounts',
      'Non.deposit.taking.MFIs.Acquired.Funds',
      'Other.Deposit.Takers.SME.depositors',
      'Other.OFIs.Number.of.Borrowers',
      'Commercial.banks.in.3.largest.cities.Number.of.Branches',
      'Non.deposit.taking.MFIs.Number.of.Customer.Accounts',
      'Non.deposit.taking.MFIs.Number.of.Customers',
      'Insurance.Corporations.Number.of.policy.holders',
      'Other.Deposit.Takers.Number.of.loan.accounts',
      'Other.OFIs.Outstanding.Loans',
      'Other.Financial.Corporations.Number.of.Customers',
      'Other.financial.intermediaries.SME.customer.accounts',
      'Other.Deposit.Takers.household.depositors',
      'Other.OFIs.Number.of.Customers',
      'Other.OFIs.Number.of.loan.accounts',
      'Other.OFIs.Acquired.Funds',
      'Non.deposit.taking.MFIs.SME.customer.accounts',
      'Commercial.banks.household.depositors',
      'Other.financial.intermediaries.Number.of.Customer.Accounts',
      'Other.Deposit.Takers.household.deposit.accounts',
      'Other.Deposit.Takers.household.borrowers',
      'Other.Deposit.Takers.household.loan.accounts',
      'Other.Deposit.Takers.SME.borrowers',
      'Commercial.banks.SME.deposit.accounts',
      'Outstanding.deposits.acquired.funds.from.all.MFIs.percent.of.GDP',
      'SME.loan.accounts.with.commercial.banks.percent.of.non.financial.corporation.borrowers.from.commercial.banks',
      'SME.depositors.with.commercial.banks.percent.of.non.financial.corporation.borrowers.from.commercial.banks',
      'SME.deposit.accounts.with.commercial.banks.percent.of.non.financial.corporation.borrowers.from.commercial.banks',
      'Number.of.active.mobile.money.accounts.per.1000.adults',
      'Number.of.active.agent.outlets.per.1000.km2',
      'Value.of.mobile.money.transactions.during.the.reference.year.percent.of.GDP',
      'Number.of.active.agent.outlets.per.100.000.adults',
      'Number.of.registered.agent.outlets.per.1000.km2',
      'Outstanding.balances.on.active.mobile.money.accounts.percent.of.GDP',
      'Number.of.mobile.money.transactions.during.the.reference.year.per.1000.adults',
      'Number.of.registered.agent.outlets.per.100.000.adults',
      'Number.of.registered.agent.outlets',
      'Number.of.active.mobile.money.accounts',
      'Number.of.registered.mobile.money.accounts',
      'Number.of.active.agent.outlets',
      'Value.of.mobile.money.transactions.during.the.reference.year',
      'Value.of.total.outstanding.mobile.banking.balances',
      'Number.of.mobile.money.transactions.during.the.reference.year',
      'Number.of.registered.mobile.money.accounts.per.1000.adults',
      'GDP.Per.Capita.USD.Current.Prices',
      'GDP.Per.Capita.LCU.Constant.Prices',
      'GDP.Per.Capita.USD.2005.Constant.Prices',
      'GDP.Per.Capita.LCU.Current.Prices',
      'Gross.Domestic.Product.LCU.Constant.Prices',
      'Gross.Domestic.Product.USD.2005.Constant.Prices',
      'Gross.Domestic.Product.USD.Current.Prices',
      'Gross.Domestic.Product.LCU.Current.Prices')

length(x) == length(colnames(fas))

colnames(fas) <- x




# this list should be in every file to clean the country names
require(stringr)
fas$Country.Name <-str_trim(fas$Country.Name)
fas$Country.Name[fas$Country.Name == "Afghanistan, I.R. of"] <- "Afghanistan"
fas$Country.Name[fas$Country.Name == "Azerbaijan, Rep. of"] <- "Azerbaijan"
fas$Country.Name[fas$Country.Name == "Bahrain, Kingdom of"] <- "Bahrain"
fas$Country.Name[fas$Country.Name == "Bosnia & Herzegovina"] <- "Bosnia and Herzegovina"
fas$Country.Name[fas$Country.Name == "Cabo Verde"] <- "Cape Verde"
fas$Country.Name[fas$Country.Name == "Central African Republic"] <- "Central African Rep."
fas$Country.Name[fas$Country.Name == "Congo, Democratic Republic of"] <- "Congo, Dem. Rep."
fas$Country.Name[fas$Country.Name == "Congo, Dem. Rep. of"] <- "Congo, Dem. Rep."
fas$Country.Name[fas$Country.Name == "China,P.R.: Mainland"] <- "China"
fas$Country.Name[fas$Country.Name == "China,P.R.:Hong Kong"] <- "Hong Kong SAR, China"
fas$Country.Name[fas$Country.Name == "China,P.R.:Macao"] <- "Macao SAR, China"
fas$Country.Name[fas$Country.Name == "Congo, Republic of"] <- "Congo, Rep."
fas$Country.Name[fas$Country.Name == "Cote D'Ivoire"] <- "Cote d'Ivoire"
fas$Country.Name[fas$Country.Name == "Cote D&#39;Ivoire"] <- "Cote d'Ivoire"
fas$Country.Name[fas$Country.Name == "C√¥te d'Ivoire"] <- "Cote d'Ivoire"
fas$Country.Name[fas$Country.Name == "Cura√ßao"] <- "Curacao"
fas$Country.Name[fas$Country.Name == "Egypt, Arab Republic of"] <- "Egypt, Arab Rep."
fas$Country.Name[fas$Country.Name == "Egypt"] <- "Egypt, Arab Rep."
fas$Country.Name[fas$Country.Name == "Faroe Islands"] <- "Faeroe Islands"
fas$Country.Name[fas$Country.Name == "Iran, Islamic Republic of"] <- "Iran, Islamic Rep."
fas$Country.Name[fas$Country.Name == "Iran, I.R. of"] <- "Iran, Islamic Rep."
fas$Country.Name[fas$Country.Name == "Korea, Republic of"] <- "Korea, Rep."
fas$Country.Name[fas$Country.Name == "Lao People's Democratic Republic"] <- "Lao PDR"
fas$Country.Name[fas$Country.Name == "Lao People&#39;s Democratic Republic"] <- "Lao PDR"
fas$Country.Name[fas$Country.Name == "Lao People's Dem.Rep"] <- "Lao PDR"
fas$Country.Name[fas$Country.Name == "Macedonia, Former Yugoslav Republic of"] <- "Macedonia, FYR"
fas$Country.Name[fas$Country.Name == "Marshall Islands"] <- "Marshall Islands"
fas$Country.Name[fas$Country.Name == "Marshall Islands,Rep"] <- "Marshall Islands"
fas$Country.Name[fas$Country.Name == "Marshall Islands, Rep."] <- "Marshall Islands"
fas$Country.Name[fas$Country.Name == "Micronesia, Fed.Sts."] <- "Micronesia, Fed. Sts."
fas$Country.Name[fas$Country.Name == "São Tomé and Principe"] <- "Sao Tome and Principe"
fas$Country.Name[fas$Country.Name == "S√£o Tom√© and Principe"] <- "Sao Tome and Principe"
fas$Country.Name[fas$Country.Name == "S√£o Tom√© & Pr√≠ncipe"] <- "Sao Tome and Principe"
fas$Country.Name[fas$Country.Name == "Venezuela, Republica Bolivariana de"] <- "Venezuela, RB"
fas$Country.Name[fas$Country.Name == "Yemen, Republic of"] <- "Yemen, Rep."
fas$Country.Name[fas$Country.Name == "Yemen"] <- "Yemen, Rep."
fas$Country.Name[fas$Country.Name == "Slovakia"] <- "Slovak Republic"
fas$Country.Name[fas$Country.Name == "Congo Republic"] <- "Congo, Dem. Rep."
fas$Country.Name[fas$Country.Name == "Saint Lucia"] <- "St. Lucia"
fas$Country.Name[fas$Country.Name == "St. Vincent & Grens."] <- "St. Vincent and the Grenadines"
fas$Country.Name[fas$Country.Name == "Serbia, Republic of"] <- "Serbia"
fas$Country.Name[fas$Country.Name == "Timor Leste"] <- "Timor-Leste"
fas$Country.Name[fas$Country.Name == "Venezuela, Rep. Bol."] <- "Venezuela"
fas$Country.Name[fas$Country.Name == "Venezuela, Republica Bolivariana de"] <- "Venezuela"
fas$Country.Name[fas$Country.Name == "South Sudan, Rep. of"] <- "South Sudan"
fas$Country.Name[fas$Country.Name == "Anguilla"] <- "Anguila"
fas$Country.Name[fas$Country.Name == "Brunei Darussalam"] <- "Brunei"

#this was Serbia and Motenegro, changed to just Serbia (they are the same Income group)
fas$Country.Name[fas$Country.Name == "Serbia and Montenegro"] <- "Serbia"

#adding country code
countries <- read.csv('Clean.data/Country.List/CountryList.csv')
fas$Country.Code <- NULL
fas <- left_join(fas, countries, 'Country.Name')

fas$Country.Code.Year <- paste(fas$Country.Code, fas$Reporting.Year, sep='')

#Converting FAS to US dollars
exchange <- read.csv('Clean.data/Combined.data/exchangerate.csv')
exchange$X <- NULL
fas.exchange <- left_join(fas, exchange, "Country.Code.Year")

fas.exchange<- fas.exchange %>%
  mutate(Commercial.banks.household.Outstanding.Deposits = Commercial.banks.household.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
         Commercial.banks.household.Outstanding.Loans = Commercial.banks.household.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
         Commercial.banks.SME.Outstanding.Deposits = Commercial.banks.SME.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Commercial.banks.SME.Outstanding.Loans = Commercial.banks.SME.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Commercial.banks.Outstanding.Deposits = Commercial.banks.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Commercial.banks.Outstanding.Loans = Commercial.banks.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Credit.unions.and.financial.cooperatives.household.Outstanding.Deposits = Credit.unions.and.financial.cooperatives.household.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Credit.unions.and.financial.cooperatives.household.Outstanding.Loans = Credit.unions.and.financial.cooperatives.household.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Credit.unions.and.financial.cooperatives.SME.Outstanding.Deposits = Credit.unions.and.financial.cooperatives.SME.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Credit.unions.and.financial.cooperatives.SME.Outstanding.Loans = Credit.unions.and.financial.cooperatives.SME.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Credit.unions.and.financial.cooperatives.Outstanding.Deposits = Credit.unions.and.financial.cooperatives.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Credit.unions.and.financial.cooperatives.Outstanding.Loans = Credit.unions.and.financial.cooperatives.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Deposit.taking.MFIs.household.Outstanding.Deposits = Deposit.taking.MFIs.household.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Deposit.taking.MFIs.household.Outstanding.Loans = Deposit.taking.MFIs.household.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Deposit.taking.MFIs.SME.Outstanding.Deposits = Deposit.taking.MFIs.SME.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Deposit.taking.MFIs.SME.Outstanding.Loans = Deposit.taking.MFIs.SME.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Deposit.taking.MFIs.Outstanding.Deposits = Deposit.taking.MFIs.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Deposit.taking.MFIs.Outstanding.Loans = Deposit.taking.MFIs.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Insurance.corporations.Life.insurance.tech.reserves = Insurance.corporations.Life.insurance.tech.reserves / Official.exchange.rate.LCU.Per.USD.period.Average,
Insurance.corporations.Non.life.insurance.tech.reserves = Insurance.corporations.Non.life.insurance.tech.reserves / Official.exchange.rate.LCU.Per.USD.period.Average,
Insurance.corporations.Outstanding.Deposits = Insurance.corporations.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Non.deposit.taking.MFIs.Acquired.Funds = Non.deposit.taking.MFIs.Acquired.Funds / Official.exchange.rate.LCU.Per.USD.period.Average,
Non.deposit.taking.MFIs.funds.from.households = Non.deposit.taking.MFIs.funds.from.households / Official.exchange.rate.LCU.Per.USD.period.Average,
Non.deposit.taking.MFIs.funds.from.SMEs = Non.deposit.taking.MFIs.funds.from.SMEs / Official.exchange.rate.LCU.Per.USD.period.Average,
Non.deposit.taking.MFIs.loans.from.households = Non.deposit.taking.MFIs.loans.from.households / Official.exchange.rate.LCU.Per.USD.period.Average,
Non.deposit.taking.MFIs.loans.from.SMEs = Non.deposit.taking.MFIs.loans.from.SMEs / Official.exchange.rate.LCU.Per.USD.period.Average,
Non.deposit.taking.MFIs.Outstanding.Loans = Non.deposit.taking.MFIs.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.Deposit.Takers.household.outstanding.deposits = Other.Deposit.Takers.household.outstanding.deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.Deposit.Takers.household.outstanding.loans = Other.Deposit.Takers.household.outstanding.loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.Deposit.Takers.SME.Outstanding.Deposits = Other.Deposit.Takers.SME.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.Deposit.Takers.SME.outstanding.loans = Other.Deposit.Takers.SME.outstanding.loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.Deposit.Takers.Outstanding.Deposits = Other.Deposit.Takers.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.Deposit.Takers.Outstanding.Loans = Other.Deposit.Takers.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.Depository.Corporations.Outstanding.Deposits = Other.Depository.Corporations.Outstanding.Deposits / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.Depository.Corporations.Outstanding.Loans = Other.Depository.Corporations.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.Financial.Corporations.Acquired.Funds = Other.Financial.Corporations.Acquired.Funds / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.financial.intermediaries.Acquired.Funds = Other.financial.intermediaries.Acquired.Funds / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.financial.intermediaries.funds.from.households = Other.financial.intermediaries.funds.from.households / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.financial.intermediaries.funds.from.SMEs = Other.financial.intermediaries.funds.from.SMEs / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.financial.intermediaries.loans.from.households = Other.financial.intermediaries.loans.from.households / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.financial.intermediaries.loans.from.SMEs = Other.financial.intermediaries.loans.from.SMEs / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.financial.intermediaries.Outstanding.Loans = Other.financial.intermediaries.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.OFIs.Acquired.Funds = Other.OFIs.Acquired.Funds / Official.exchange.rate.LCU.Per.USD.period.Average,
Other.OFIs.Outstanding.Loans = Other.OFIs.Outstanding.Loans / Official.exchange.rate.LCU.Per.USD.period.Average,
Outstanding.deposits.of.nonfinancial.corporations.and.households.IFS = Outstanding.deposits.of.nonfinancial.corporations.and.households.IFS / Official.exchange.rate.LCU.Per.USD.period.Average,
Outstanding.loans.of.nonfinancial.corporations.and.households.IFS = Outstanding.loans.of.nonfinancial.corporations.and.households.IFS / Official.exchange.rate.LCU.Per.USD.period.Average)

#Changing the zeros to NAs
fas.exchange[fas.exchange == 0] <- NA

# Redoing names to indicated what is in USD
x<- c('Country.Name',
      'Reporting.Year',
      'Commercial.banks.SME.borrowers',
      'Commercial.banks.SME.loan.accounts',
      'Commercial.banks.SME.Outstanding.Deposits.USD',
      'Commercial.banks.SME.Outstanding.Loans.USD',
      'Credit.unions.and.financial.cooperatives.household.borrowers',
      'Credit.unions.and.financial.cooperatives.household.depositors',
      'Credit.unions.and.financial.cooperatives.household.loan.accounts',
      'Credit.unions.and.financial.cooperatives.household.Outstanding.Deposits.USD',
      'Credit.unions.and.financial.cooperatives.household.Outstanding.Loans.USD',
      'Credit.unions.and.financial.cooperatives.in.3.largest.cities.Number.of.Branches',
      'Credit.unions.and.financial.cooperatives.SME.borrowers',
      'Credit.unions.and.financial.cooperatives.SME.depositors',
      'Credit.unions.and.financial.cooperatives.SME.loan.accounts',
      'Credit.unions.and.financial.cooperatives.SME.Outstanding.Deposits.USD',
      'Credit.unions.and.financial.cooperatives.SME.Outstanding.Loans.USD',
      'Deposit.taking.MFIs.household.borrowers',
      'Deposit.taking.MFIs.household.depositors',
      'Deposit.taking.MFIs.household.loan.accounts',
      'Deposit.taking.MFIs.household.Outstanding.Deposits.USD',
      'Deposit.taking.MFIs.household.Outstanding.Loans.USD',
      'Deposit.taking.MFIs.in.3.largest.cities.Number.of.Branches',
      'Deposit.taking.MFIs.SME.borrowers',
      'Deposit.taking.MFIs.SME.depositors',
      'Deposit.taking.MFIs.SME.loan.accounts',
      'Deposit.taking.MFIs.SME.Outstanding.Deposits.USD',
      'Deposit.taking.MFIs.SME.Outstanding.Loans.USD',
      'Insurance.corporations.Life.insurance.policies',
      'Insurance.Corporations.Life.insurance.policy.holders',
      'Insurance.corporations.Life.insurance.tech.reserves.USD',
      'Insurance.corporations.Non.life.insurance.policies',
      'Insurance.Corporations.Non.life.insurance.policy.holders',
      'Insurance.corporations.Non.life.insurance.tech.reserves.USD',
      'Non.deposit.taking.MFIs.funds.from.households.USD',
      'Non.deposit.taking.MFIs.funds.from.SMEs.USD',
      'Non.deposit.taking.MFIs.household.borrowers',
      'Non.deposit.taking.MFIs.household.loan.accounts',
      'Non.deposit.taking.MFIs.in.3.largest.cities.Number.of.Branches',
      'Non.deposit.taking.MFIs.loans.from.households.USD',
      'Non.deposit.taking.MFIs.loans.from.SMEs.USD',
      'Non.deposit.taking.MFIs.SME.borrowers',
      'Non.deposit.taking.MFIs.SME.loan.accounts',
      'Other.deposit.takers.in.3.largest.cities.Number.of.Branches',
      'Other.financial.intermediaries.funds.from.households.USD',
      'Other.financial.intermediaries.funds.from.SMEs.USD',
      'Other.financial.intermediaries.household.borrowers',
      'Other.financial.intermediaries.household.loan.accounts',
      'Other.financial.intermediaries.loans.from.households.USD',
      'Other.financial.intermediaries.loans.from.SMEs.USD',
      'Other.financial.intermediaries.SME.borrowers',
      'Other.financial.intermediaries.SME.loan.accounts',
      'Non.deposit.taking.MFIs.household.customers',
      'Non.deposit.taking.MFIs.SME.customers',
      'Other.financial.intermediaries.household.customers',
      'Other.financial.intermediaries.SME.customers',
      'Commercial.banks.household.borrowers',
      'Non.deposit.taking.MFIs.Number.of.Borrowers',
      'Non.deposit.taking.MFIs.Number.of.loan.accounts',
      'Non.deposit.taking.MFIs.Outstanding.Loans.USD',
      'of.which.non.deposit.taking.MFIs',
      'Non.deposit.taking.MFIs.Number.of.Branches',
      'Other.financial.intermediaries.in.3.largest.cities.Number.of.Branches',
      'Other.OFIs.Number.of.Branches',
      'Commercial.banks.Number.of.Borrowers',
      'Commercial.banks.Number.of.Deposit.Accounts',
      'Commercial.banks.Number.of.loan.accounts',
      'Commercial.banks.household.loan.accounts',
      'Commercial.banks.household.Outstanding.Deposits.USD',
      'Commercial.banks.household.Outstanding.Loans.USD',
      'Commercial.banks.Outstanding.Deposits.USD',
      'Commercial.banks.Outstanding.Loans.USD',
      'Credit.unions.and.financial.cooperatives',
      'Credit.unions.and.financial.cooperatives.Number.of.Borrowers',
      'Credit.unions.and.financial.cooperatives.Number.of.Branches',
      'Credit.unions.and.financial.cooperatives.Number.of.Deposit.Accounts',
      'Credit.unions.and.financial.cooperatives.Number.of.Depositors',
      'Credit.unions.and.financial.cooperatives.Number.of.loan.accounts',
      'Credit.unions.and.financial.cooperatives.Outstanding.Deposits.USD',
      'Credit.unions.and.financial.cooperatives.Outstanding.Loans.USD',
      'Deposit.taking.MFIs.Number.of.Borrowers',
      'Deposit.taking.MFIs.Number.of.Branches',
      'Deposit.taking.MFIs.Number.of.Deposit.Accounts',
      'Deposit.taking.MFIs.Number.of.Depositors',
      'Deposit.taking.MFIs.Number.of.loan.accounts',
      'Deposit.taking.MFIs.Outstanding.Deposits.USD',
      'Deposit.taking.MFIs.Outstanding.Loans.USD',
      'Insurance.Corporations',
      'Insurance.corporations.Outstanding.Deposits.USD',
      'Number.of.Automated.Teller.Machines',
      'Number.of.Automated.Teller.Machines.3.largest.cities',
      'Other.deposit.takers.Number.of.Branches',
      'Other.deposit.takers.Number.of.Deposit.Accounts',
      'Other.Depository.Corporations',
      'Other.Depository.Corporations.Number.of.Borrowers',
      'Other.Depository.Corporations.Number.of.Branches',
      'Other.Depository.Corporations.Number.of.Deposit.Accounts',
      'Other.Depository.Corporations.Number.of.Depositors',
      'Other.Depository.Corporations.Number.of.loan.accounts',
      'Other.Depository.Corporations.Outstanding.Deposits.USD',
      'Other.Depository.Corporations.Outstanding.Loans.USD',
      'Other.Financial.Corporations',
      'Other.financial.intermediaries.Number.of.Borrowers',
      'Other.financial.intermediaries.Number.of.Branches',
      'Other.financial.intermediaries.Number.of.loan.accounts',
      'Other.financial.intermediaries.Outstanding.Loans.USD',
      'Outstanding.deposits.of.nonfinancial.corporations.and.households.IFS.USD',
      'Outstanding.loans.of.nonfinancial.corporations.and.households.IFS.USD',
      'SME.borrowers.from.commercial.banks.of.non.financial.corporation.borrowers.from.commercial.banks',
      'Credit.union.and.financial.cooperative.branches.per.100.000.adults',
      'Outstanding.loans.from.commercial.banks.percent.of.GDP',
      'Adult.Population',
      'Land.mass.of.country.in.Kilometers',
      'Outstanding.deposits.with.credit.unions.and.financial.cooperatives.percent.of.GDP',
      'Borrowers.from.credit.unions.and.financial.cooperatives.per.1000.adults',
      'Commercial.bank.branches.per.100.000.adults',
      'All.MFI.branches.per.1000.km2',
      'Depositors.with.commercial.banks.per.1000.adults',
      'ATMs.per.100.000.adults',
      'Borrowers.from.commercial.banks.per.1000.adults',
      'Outstanding.household.deposits.with.commercial.banks.percent.of.GDP',
      'Credit.union.and.financial.cooperative.branches.per.1000.km2',
      'Loan.accounts.with.commercial.banks.per.1000.adults',
      'Commercial.bank.branches.per.1000.km2',
      'ATMs.per.1000.km2',
      'Borrowers.from.all.MFIs.per.1000.adults',
      'Household.deposit.accounts.with.commercial.banks.per.1000.adults',
      'Outstanding.deposits.with.commercial.banks.percent.of.GDP',
      'Household.depositors.with.commercial.banks.per.1000.adults',
      'Outstanding.SME.loans.from.commercial.banks.percent.of.GDP.',
      'Household.loan.accounts.with.commercial.banks.per.1000.adults',
      'Outstanding.loans.from.credit.unions.and.financial.cooperatives.percent.of.GDP',
      'Outstanding.household.loans.from.commercial.banks.percent.of.GDP',
      'Deposit.accounts.with.commercial.banks.per.1000.adults',
      'Depositors.with.credit.unions.and.financial.cooperatives.per.1000.adults',
      'Outstanding.loans.from.all.MFIs.percent.of.GDP',
      'Outstanding.SME.deposits.with.commercial.banks.percent.of.GDP',
      'Deposit.customer.accounts.with.all.MFIs.per.1000.adults',
      'Loan.accounts.with.credit.unions.and.financial.cooperatives.per.1000.adults',
      'All.MFI.branches.per.100.000.adults',
      'Depositors.customers.with.all.MFIs.per.1000.adults',
      'Household.borrowers.from.commercial.banks.per.1000.adults',
      'Loan.accounts.with.all.MFIs.per.1000.adults',
      'Deposit.accounts.with.credit.unions.and.financial.cooperatives.per.1000.adults',
      'Other.Financial.Corporations.Acquired.Funds.USD',
      'Deposit.taking.MFIs.SME.deposit.accounts',
      'Credit.unions.and.financial.cooperatives.SME.deposit.accounts',
      'Other.OFIs.Number.of.Customer.Accounts',
      'Other.financial.intermediaries.household.customer.accounts',
      'Deposit.taking.MFIs.household.deposit.accounts',
      'Commercial.banks.Number.of.Branches',
      'Other.Deposit.Takers.household.outstanding.loans.USD',
      'Other.Deposit.Takers.household.outstanding.deposits.USD',
      'Other.Deposit.Takers.Outstanding.Loans.USD',
      'Other.Deposit.Takers.SME.Outstanding.Deposits.USD',
      'Other.financial.intermediaries.Number.of.Customers',
      'Other.Deposit.Takers.Outstanding.Deposits.USD',
      'Other.Financial.Corporations.Number.of.Customer.Accounts',
      'Other.financial.intermediaries',
      'Other.Deposit.Takers.Number.of.Borrowers',
      'Insurance.corporations.Number.of.policies',
      'Other.Deposit.Takers.Number.of.Depositors',
      'Commercial.banks.SME.depositors',
      'Commercial.banks.household.deposit.accounts',
      'Non.deposit.taking.MFIs.household.customer.accounts',
      'Other.Deposit.Takers',
      'Deposit.taking.microfinance.institutions',
      'Commercial.banks',
      'Other.Deposit.Takers.SME.outstanding.loans.USD',
      'Other.financial.intermediaries.Acquired.Funds.USD',
      'Commercial.banks.Number.of.Depositors',
      'Other.Deposit.Takers.SME.loan.accounts',
      'Credit.unions.and.financial.cooperatives.household.deposit.accounts',
      'Other.Deposit.Takers.SME.deposit.accounts',
      'Non.deposit.taking.MFIs.Acquired.Funds.USD',
      'Other.Deposit.Takers.SME.depositors',
      'Other.OFIs.Number.of.Borrowers',
      'Commercial.banks.in.3.largest.cities.Number.of.Branches',
      'Non.deposit.taking.MFIs.Number.of.Customer.Accounts',
      'Non.deposit.taking.MFIs.Number.of.Customers',
      'Insurance.Corporations.Number.of.policy.holders',
      'Other.Deposit.Takers.Number.of.loan.accounts',
      'Other.OFIs.Outstanding.Loans.USD',
      'Other.Financial.Corporations.Number.of.Customers',
      'Other.financial.intermediaries.SME.customer.accounts',
      'Other.Deposit.Takers.household.depositors',
      'Other.OFIs.Number.of.Customers',
      'Other.OFIs.Number.of.loan.accounts',
      'Other.OFIs.Acquired.Funds.USD',
      'Non.deposit.taking.MFIs.SME.customer.accounts',
      'Commercial.banks.household.depositors',
      'Other.financial.intermediaries.Number.of.Customer.Accounts',
      'Other.Deposit.Takers.household.deposit.accounts',
      'Other.Deposit.Takers.household.borrowers',
      'Other.Deposit.Takers.household.loan.accounts',
      'Other.Deposit.Takers.SME.borrowers',
      'Commercial.banks.SME.deposit.accounts',
      'Outstanding.deposits.acquired.funds.from.all.MFIs.percent.of.GDP',
      'SME.loan.accounts.with.commercial.banks.percent.of.non.financial.corporation.borrowers.from.commercial.banks',
      'SME.depositors.with.commercial.banks.percent.of.non.financial.corporation.borrowers.from.commercial.banks',
      'SME.deposit.accounts.with.commercial.banks.percent.of.non.financial.corporation.borrowers.from.commercial.banks',
      'Number.of.active.mobile.money.accounts.per.1000.adults',
      'Number.of.active.agent.outlets.per.1000.km2',
      'Value.of.mobile.money.transactions.during.the.reference.year.percent.of.GDP',
      'Number.of.active.agent.outlets.per.100.000.adults',
      'Number.of.registered.agent.outlets.per.1000.km2',
      'Outstanding.balances.on.active.mobile.money.accounts.percent.of.GDP',
      'Number.of.mobile.money.transactions.during.the.reference.year.per.1000.adults',
      'Number.of.registered.agent.outlets.per.100.000.adults',
      'Number.of.registered.agent.outlets',
      'Number.of.active.mobile.money.accounts',
      'Number.of.registered.mobile.money.accounts',
      'Number.of.active.agent.outlets',
      'Value.of.mobile.money.transactions.during.the.reference.year',
      'Value.of.total.outstanding.mobile.banking.balances',
      'Number.of.mobile.money.transactions.during.the.reference.year',
      'Number.of.registered.mobile.money.accounts.per.1000.adults',
      'GDP.Per.Capita.USD.Current.Prices',
      'GDP.Per.Capita.LCU.Constant.Prices',
      'GDP.Per.Capita.USD.2005.Constant.Prices',
      'GDP.Per.Capita.LCU.Current.Prices',
      'Gross.Domestic.Product.LCU.Constant.Prices',
      'Gross.Domestic.Product.USD.2005.Constant.Prices',
      'Gross.Domestic.Product.USD.Current.Prices',
      'Gross.Domestic.Product.LCU.Current.Prices',
      'Country.Code',
      'Country.Code.Year',
      'Official.exchange.rate.LCU.Per.USD.period.Average')

length(x) == length(colnames(fas.exchange))

colnames(fas.exchange) <- x


#final write to file
write.csv(fas.exchange, file = 'Clean.data/fas.csv')

