library(openxlsx)
library(dplyr)
library(magrittr)
library(tidyr)

# Global Findex (WB)
# Downloaded All Countries and all attribues for 2014 survey
findex <- read.csv('Data/ExternalDBs/Data_Extract_From_Global_Findex_(Global_Financial_Inclusion_Database)_Data.csv', sep=',')

#pull out just 'wave 2', or the 2014 data for analysis
findex <- filter(findex, grepl('w2', Series.Name))

#Delete unneeded column
findex$Series.Code <- NULL

#setting the percentages as actual percentages (deviding X2014..YR2014. by 100 )
#test<- transform(findex, X2014<- X2014..YR2014. / 100)


#swing the data so that each country is a row and all the measured attribues are columns
# there are 156 counties in this database
findex<- spread(findex, key = Series.Name, value = X2014..YR2014.)

#NAs are '..'
findex[findex == '..'] <- NA

x<- c('Country.Name',
      'Country.Code',
      'Account.age.15',
      'Account.at.a.financial.institution.age.15',
      'Account.at.a.financial.institution.female.age.15',
      'Account.at.a.financial.institution.income.poorest.40.ages.15',
      'Account.at.a.financial.institution.income.richest.60.ages.15',
      'Account.at.a.financial.institution.male.age.15',
      'Account.at.a.financial.institution.older.adults.ages.25',
      'Account.at.a.financial.institution.primary.education.or.less.ages.15',
      'Account.at.a.financial.institution.rural.age.15',
      'Account.at.a.financial.institution.secondary.education.or.more.ages.15',
      'Account.at.a.financial.institution.young.adults.ages.15.24',
      'Account.female.age.15',
      'Account.income.poorest.40.ages.15',
      'Account.income.richest.60.ages.15',
      'Account.male.age.15',
      'Account.older.adults.ages.25',
      'Account.primary.education.or.less.ages.15',
      'Account.rural.age.15',
      'Account.secondary.education.or.more.ages.15',
      'Account.young.adults.ages.15.24',
      'Borrowed.any.money.in.the.past.year.age.15',
      'Borrowed.any.money.in.the.past.year.female.age.15',
      'Borrowed.any.money.in.the.past.year.income.poorest.40.ages.15',
      'Borrowed.any.money.in.the.past.year.income.richest.60.ages.15',
      'Borrowed.any.money.in.the.past.year.male.age.15',
      'Borrowed.any.money.in.the.past.year.older.adults.ages.25',
      'Borrowed.any.money.in.the.past.year.primary.education.or.less.ages.15',
      'Borrowed.any.money.in.the.past.year.rural.age.15',
      'Borrowed.any.money.in.the.past.year.secondary.education.or.more.ages.15',
      'Borrowed.any.money.in.the.past.year.young.adults.ages.15.24',
      'Borrowed.for.education.or.school.fees.age.15',
      'Borrowed.for.education.or.school.fees.female.age.15',
      'Borrowed.for.education.or.school.fees.income.poorest.40.ages.15',
      'Borrowed.for.education.or.school.fees.income.richest.60.ages.15',
      'Borrowed.for.education.or.school.fees.male.age.15',
      'Borrowed.for.education.or.school.fees.older.adults.ages.25',
      'Borrowed.for.education.or.school.fees.primary.education.or.less.ages.15',
      'Borrowed.for.education.or.school.fees.rural.age.15',
      'Borrowed.for.education.or.school.fees.secondary.education.or.more.ages.15',
      'Borrowed.for.education.or.school.fees.young.adults.ages.15.24',
      'Borrowed.for.health.or.medical.purposes.age.15',
      'Borrowed.for.health.or.medical.purposes.female.age.15',
      'Borrowed.for.health.or.medical.purposes.income.poorest.40.ages.15',
      'Borrowed.for.health.or.medical.purposes.income.richest.60.ages.15',
      'Borrowed.for.health.or.medical.purposes.male.age.15',
      'Borrowed.for.health.or.medical.purposes.older.adults.ages.25',
      'Borrowed.for.health.or.medical.purposes.primary.education.or.less.ages.15',
      'Borrowed.for.health.or.medical.purposes.rural.age.15',
      'Borrowed.for.health.or.medical.purposes.secondary.education.or.more.ages.15',
      'Borrowed.for.health.or.medical.purposes.young.adults.ages.15.24',
      'Borrowed.from.a.financial.institution.age.15',
      'Borrowed.from.a.financial.institution.female.age.15',
      'Borrowed.from.a.financial.institution.income.poorest.40.ages.15',
      'Borrowed.from.a.financial.institution.income.richest.60.ages.15',
      'Borrowed.from.a.financial.institution.male.age.15',
      'Borrowed.from.a.financial.institution.older.adults.ages.25',
      'Borrowed.from.a.financial.institution.primary.education.or.less.ages.15',
      'Borrowed.from.a.financial.institution.rural.age.15',
      'Borrowed.from.a.financial.institution.secondary.education.or.more.ages.15',
      'Borrowed.from.a.financial.institution.young.adults.ages.15.24',
      'Borrowed.from.a.private.informal.lender.age.15',
      'Borrowed.from.a.private.informal.lender.female.age.15',
      'Borrowed.from.a.private.informal.lender.income.poorest.40.ages.15',
      'Borrowed.from.a.private.informal.lender.income.richest.60.ages.15',
      'Borrowed.from.a.private.informal.lender.male.age.15',
      'Borrowed.from.a.private.informal.lender.older.adults.ages.25',
      'Borrowed.from.a.private.informal.lender.primary.education.or.less.ages.15',
      'Borrowed.from.a.private.informal.lender.rural.age.15',
      'Borrowed.from.a.private.informal.lender.secondary.education.or.more.ages.15',
      'Borrowed.from.a.private.informal.lender.young.adults.ages.15.24',
      'Borrowed.from.a.store.by.buying.on.credit.age.15',
      'Borrowed.from.a.store.by.buying.on.credit.female.age.15',
      'Borrowed.from.a.store.by.buying.on.credit.income.poorest.40.ages.15',
      'Borrowed.from.a.store.by.buying.on.credit.income.richest.60.ages.15',
      'Borrowed.from.a.store.by.buying.on.credit.male.age.15',
      'Borrowed.from.a.store.by.buying.on.credit.older.adults.ages.25',
      'Borrowed.from.a.store.by.buying.on.credit.primary.education.or.less.ages.15',
      'Borrowed.from.a.store.by.buying.on.credit.rural.age.15',
      'Borrowed.from.a.store.by.buying.on.credit.secondary.education.or.more.ages.15',
      'Borrowed.from.a.store.by.buying.on.credit.young.adults.ages.15.24',
      'Borrowed.from.family.or.friends.age.15',
      'Borrowed.from.family.or.friends.female.age.15',
      'Borrowed.from.family.or.friends.income.poorest.40.ages.15',
      'Borrowed.from.family.or.friends.income.richest.60.ages.15',
      'Borrowed.from.family.or.friends.male.age.15',
      'Borrowed.from.family.or.friends.older.adults.ages.25',
      'Borrowed.from.family.or.friends.primary.education.or.less.ages.15',
      'Borrowed.from.family.or.friends.rural.age.15',
      'Borrowed.from.family.or.friends.secondary.education.or.more.ages.15',
      'Borrowed.from.family.or.friends.young.adults.ages.15.24',
      'Borrowed.to.start.operate.or.expand.a.farm.or.business.age.15',
      'Borrowed.to.start.operate.or.expand.a.farm.or.business.female.age.15',
      'Borrowed.to.start.operate.or.expand.a.farm.or.business.income.poorest.40.ages.15',
      'Borrowed.to.start.operate.or.expand.a.farm.or.business.income.richest.60.ages.15',
      'Borrowed.to.start.operate.or.expand.a.farm.or.business.male.age.15',
      'Borrowed.to.start.operate.or.expand.a.farm.or.business.older.adults.ages.25',
      'Borrowed.to.start.operate.or.expand.a.farm.or.business.primary.education.or.less.ages.15',
      'Borrowed.to.start.operate.or.expand.a.farm.or.business.rural.age.15',
      'Borrowed.to.start.operate.or.expand.a.farm.or.business.secondary.education.or.more.ages.15',
      'Borrowed.to.start.operate.or.expand.a.farm.or.business.young.adults.ages.15.24',
      'Coming.up.with.emergency.funds.not.at.all.possible.age.15',
      'Coming.up.with.emergency.funds.not.at.all.possible.female.age.15',
      'Coming.up.with.emergency.funds.not.at.all.possible.income.poorest.40.ages.15',
      'Coming.up.with.emergency.funds.not.at.all.possible.income.richest.60.ages.15',
      'Coming.up.with.emergency.funds.not.at.all.possible.male.age.15',
      'Coming.up.with.emergency.funds.not.at.all.possible.older.adults.ages.25',
      'Coming.up.with.emergency.funds.not.at.all.possible.primary.education.or.less.ages.15',
      'Coming.up.with.emergency.funds.not.at.all.possible.rural.age.15',
      'Coming.up.with.emergency.funds.not.at.all.possible.secondary.education.or.more.ages.15',
      'Coming.up.with.emergency.funds.not.at.all.possible.young.adults.ages.15.24',
      'Coming.up.with.emergency.funds.not.very.possible.age.15',
      'Coming.up.with.emergency.funds.not.very.possible.female.age.15',
      'Coming.up.with.emergency.funds.not.very.possible.income.poorest.40.ages.15',
      'Coming.up.with.emergency.funds.not.very.possible.income.richest.60.ages.15',
      'Coming.up.with.emergency.funds.not.very.possible.male.age.15',
      'Coming.up.with.emergency.funds.not.very.possible.older.adults.ages.25',
      'Coming.up.with.emergency.funds.not.very.possible.primary.education.or.less.ages.15',
      'Coming.up.with.emergency.funds.not.very.possible.rural.age.15',
      'Coming.up.with.emergency.funds.not.very.possible.secondary.education.or.more.ages.15',
      'Coming.up.with.emergency.funds.not.very.possible.young.adults.ages.15.24',
      'Coming.up.with.emergency.funds.somewhat.possible.age.15',
      'Coming.up.with.emergency.funds.somewhat.possible.female.age.15',
      'Coming.up.with.emergency.funds.somewhat.possible.income.poorest.40.ages.15',
      'Coming.up.with.emergency.funds.somewhat.possible.income.richest.60.ages.15',
      'Coming.up.with.emergency.funds.somewhat.possible.male.age.15',
      'Coming.up.with.emergency.funds.somewhat.possible.older.adults.ages.25',
      'Coming.up.with.emergency.funds.somewhat.possible.primary.education.or.less.ages.15',
      'Coming.up.with.emergency.funds.somewhat.possible.rural.age.15',
      'Coming.up.with.emergency.funds.somewhat.possible.secondary.education.or.more.ages.15',
      'Coming.up.with.emergency.funds.somewhat.possible.young.adults.ages.15.24',
      'Coming.up.with.emergency.funds.very.possible.age.15',
      'Coming.up.with.emergency.funds.very.possible.female.age.15',
      'Coming.up.with.emergency.funds.very.possible.income.poorest.40.ages.15',
      'Coming.up.with.emergency.funds.very.possible.income.richest.60.ages.15',
      'Coming.up.with.emergency.funds.very.possible.male.age.15',
      'Coming.up.with.emergency.funds.very.possible.older.adults.ages.25',
      'Coming.up.with.emergency.funds.very.possible.primary.education.or.less.ages.15',
      'Coming.up.with.emergency.funds.very.possible.rural.age.15',
      'Coming.up.with.emergency.funds.very.possible.secondary.education.or.more.ages.15',
      'Coming.up.with.emergency.funds.very.possible.young.adults.ages.15.24',
      'Credit.card.age.15',
      'Credit.card.female.age.15',
      'Credit.card.income.poorest.40.ages.15',
      'Credit.card.income.richest.60.ages.15',
      'Credit.card.male.age.15',
      'Credit.card.older.adults.ages.25',
      'Credit.card.primary.education.or.less.ages.15',
      'Credit.card.rural.age.15',
      'Credit.card.secondary.education.or.more.ages.15',
      'Credit.card.used.in.the.past.year.age.15',
      'Credit.card.used.in.the.past.year.female.age.15',
      'Credit.card.used.in.the.past.year.income.poorest.40.ages.15',
      'Credit.card.used.in.the.past.year.income.richest.60.ages.15',
      'Credit.card.used.in.the.past.year.male.age.15',
      'Credit.card.used.in.the.past.year.older.adults.ages.25',
      'Credit.card.used.in.the.past.year.primary.education.or.less.ages.15',
      'Credit.card.used.in.the.past.year.rural.age.15',
      'Credit.card.used.in.the.past.year.secondary.education.or.more.ages.15',
      'Credit.card.used.in.the.past.year.young.adults.ages.15.24',
      'Credit.card.young.adults.ages.15.24',
      'Debit.card.age.15',
      'Debit.card.female.age.15',
      'Debit.card.income.poorest.40.ages.15',
      'Debit.card.income.richest.60.ages.15',
      'Debit.card.in.own.name.age.15',
      'Debit.card.in.own.name.female.age.15',
      'Debit.card.in.own.name.income.poorest.40.ages.15',
      'Debit.card.in.own.name.income.richest.60.ages.15',
      'Debit.card.in.own.name.male.age.15',
      'Debit.card.in.own.name.older.adults.ages.25',
      'Debit.card.in.own.name.primary.education.or.less.ages.15',
      'Debit.card.in.own.name.rural.age.15',
      'Debit.card.in.own.name.secondary.education.or.more.ages.15',
      'Debit.card.in.own.name.young.adults.ages.15.24',
      'Debit.card.male.age.15',
      'Debit.card.older.adults.ages.25',
      'Debit.card.primary.education.or.less.ages.15',
      'Debit.card.rural.age.15',
      'Debit.card.secondary.education.or.more.ages.15',
      'Debit.card.used.in.the.past.year.age.15',
      'Debit.card.used.in.the.past.year.female.age.15',
      'Debit.card.used.in.the.past.year.income.poorest.40.ages.15',
      'Debit.card.used.in.the.past.year.income.richest.60.ages.15',
      'Debit.card.used.in.the.past.year.male.age.15',
      'Debit.card.used.in.the.past.year.older.adults.ages.25',
      'Debit.card.used.in.the.past.year.primary.education.or.less.ages.15',
      'Debit.card.used.in.the.past.year.rural.age.15',
      'Debit.card.used.in.the.past.year.secondary.education.or.more.ages.15',
      'Debit.card.used.in.the.past.year.young.adults.ages.15.24',
      'Debit.card.young.adults.ages.15.24',
      'Deposit.in.the.past.year.with.an.account.age.15',
      'Deposits.in.a.typical.month.0.with.an.account.age.15',
      'Deposits.in.a.typical.month.1.or.2.with.an.account.age.15',
      'Deposits.in.a.typical.month.3.with.an.account.age.15',
      'Made.transaction.from.an.account.at.a.financial.institution.using.a.mobile.phone.with.an.account.age.15',
      'Main.mode.of.withdrawal.ATM.with.an.account.age.15',
      'Main.mode.of.withdrawal.bank.agent.with.an.account.age.15',
      'Main.mode.of.withdrawal.bank.teller.with.an.account.age.15',
      'Main.mode.of.withdrawal.other.with.an.account.age.15',
      'Main.source.of.emergency.funds.family.or.friends.able.to.raise.funds.age.15',
      'Main.source.of.emergency.funds.financial.institution.or.credit.card.able.to.raise.funds.age.15',
      'Main.source.of.emergency.funds.other.able.to.raise.funds.age.15',
      'Main.source.of.emergency.funds.private.informal.lender.able.to.raise.funds.age.15',
      'Main.source.of.emergency.funds.savings.able.to.raise.funds.age.15',
      'Main.source.of.emergency.funds.work.or.loan.from.employer.able.to.raise.funds.age.15',
      'Mobile.account.age.15',
      'Mobile.account.female.age.15',
      'Mobile.account.income.poorest.40.ages.15',
      'Mobile.account.income.richest.60.ages.15',
      'Mobile.account.male.age.15',
      'Mobile.account.older.adults.ages.25',
      'Mobile.account.primary.education.or.less.ages.15',
      'Mobile.account.rural.age.15',
      'Mobile.account.secondary.education.or.more.ages.15',
      'Mobile.account.young.adults.ages.15.24',
      'No.deposit.and.no.withdrawal.in.the.past.year.with.an.account.age.15',
      'Outstanding.mortgage.age.15',
      'Outstanding.mortgage.female.age.15',
      'Outstanding.mortgage.income.poorest.40.ages.15',
      'Outstanding.mortgage.income.richest.60.ages.15',
      'Outstanding.mortgage.male.age.15',
      'Outstanding.mortgage.older.adults.ages.25',
      'Outstanding.mortgage.primary.education.or.less.ages.15',
      'Outstanding.mortgage.rural.age.15',
      'Outstanding.mortgage.secondary.education.or.more.ages.15',
      'Outstanding.mortgage.young.adults.ages.15.24',
      'Paid.school.fees.in.the.past.year.age.15',
      'Paid.school.fees.in.the.past.year.female.age.15',
      'Paid.school.fees.in.the.past.year.income.poorest.40.ages.15',
      'Paid.school.fees.in.the.past.year.income.richest.60.ages.15',
      'Paid.school.fees.in.the.past.year.male.age.15',
      'Paid.school.fees.in.the.past.year.older.adults.ages.25',
      'Paid.school.fees.in.the.past.year.primary.education.or.less.ages.15',
      'Paid.school.fees.in.the.past.year.rural.age.15',
      'Paid.school.fees.in.the.past.year.secondary.education.or.more.ages.15',
      'Paid.school.fees.in.the.past.year.young.adults.ages.15.24',
      'Paid.school.fees.using.a.mobile.phone.paying.school.fees.age.15',
      'Paid.school.fees.using.an.account.at.a.financial.institution.paying.school.fees.age.15',
      'Paid.school.fees.using.cash.paying.school.fees.age.15',
      'Paid.utility.bills.in.the.past.year.age.15',
      'Paid.utility.bills.in.the.past.year.female.age.15',
      'Paid.utility.bills.in.the.past.year.income.poorest.40.ages.15',
      'Paid.utility.bills.in.the.past.year.income.richest.60.ages.15',
      'Paid.utility.bills.in.the.past.year.male.age.15',
      'Paid.utility.bills.in.the.past.year.older.adults.ages.25',
      'Paid.utility.bills.in.the.past.year.primary.education.or.less.ages.15',
      'Paid.utility.bills.in.the.past.year.rural.age.15',
      'Paid.utility.bills.in.the.past.year.secondary.education.or.more.ages.15',
      'Paid.utility.bills.in.the.past.year.young.adults.ages.15.24',
      'Paid.utility.bills.using.a.mobile.phone.paying.utility.bills.age.15',
      'Paid.utility.bills.using.an.account.at.a.financial.institution.paying.utility.bills.age.15',
      'Paid.utility.bills.using.cash.paying.utility.bills.age.15',
      'Received.domestic.remittances.in.person.and.in.cash.recipients.age.15',
      'Received.domestic.remittances.in.the.past.year.age.15',
      'Received.domestic.remittances.in.the.past.year.female.age.15',
      'Received.domestic.remittances.in.the.past.year.income.poorest.40.ages.15',
      'Received.domestic.remittances.in.the.past.year.income.richest.60.ages.15',
      'Received.domestic.remittances.in.the.past.year.male.age.15',
      'Received.domestic.remittances.in.the.past.year.older.adults.ages.25',
      'Received.domestic.remittances.in.the.past.year.primary.education.or.less.ages.15',
      'Received.domestic.remittances.in.the.past.year.rural.age.15',
      'Received.domestic.remittances.in.the.past.year.secondary.education.or.more.ages.15',
      'Received.domestic.remittances.in.the.past.year.young.adults.ages.15.24',
      'Received.domestic.remittances.through.a.financial.institution.recipients.age.15',
      'Received.domestic.remittances.through.a.mobile.phone.recipients.age.15',
      'Received.domestic.remittances.through.a.money.transfer.service.recipients.age.15',
      'Received.government.transfers.in.cash.transfer.recipients.age.15',
      'Received.government.transfers.in.the.past.year.age.15',
      'Received.government.transfers.in.the.past.year.female.age.15',
      'Received.government.transfers.in.the.past.year.income.poorest.40.ages.15',
      'Received.government.transfers.in.the.past.year.income.richest.60.ages.15',
      'Received.government.transfers.in.the.past.year.male.age.15',
      'Received.government.transfers.in.the.past.year.older.adults.ages.25',
      'Received.government.transfers.in.the.past.year.primary.education.or.less.ages.15',
      'Received.government.transfers.in.the.past.year.rural.age.15',
      'Received.government.transfers.in.the.past.year.secondary.education.or.more.ages.15',
      'Received.government.transfers.in.the.past.year.young.adults.ages.15.24',
      'Received.government.transfers.into.an.account.at.a.financial.institution.transfer.recipients.age.15',
      'Received.government.transfers.into.a.new.and.first.account.cashless.transfer.recipients.age.15',
      'Received.government.transfers.into.a.new.but.not.first.account.cashless.transfer.recipients.age.15',
      'Received.government.transfers.into.a.pre.existing.account.cashless.transfer.recipients.age.15',
      'Received.government.transfers.through.a.mobile.phone.transfer.recipients.age.15',
      'Received.government.transfers.withdraw.all.right.away.cashless.transfer.recipients.age.15',
      'Received.government.transfers.withdraw.over.time.as.needed.cashless.transfer.recipients.age.15',
      'Received.payments.for.agricultural.products.in.cash.recipients.age.15',
      'Received.payments.for.agricultural.products.in.the.past.year.age.15',
      'Received.payments.for.agricultural.products.in.the.past.year.female.age.15',
      'Received.payments.for.agricultural.products.in.the.past.year.income.poorest.40.ages.15',
      'Received.payments.for.agricultural.products.in.the.past.year.income.richest.60.ages.15',
      'Received.payments.for.agricultural.products.in.the.past.year.male.age.15',
      'Received.payments.for.agricultural.products.in.the.past.year.older.adults.ages.25',
      'Received.payments.for.agricultural.products.in.the.past.year.primary.education.or.less.ages.15',
      'Received.payments.for.agricultural.products.in.the.past.year.rural.age.15',
      'Received.payments.for.agricultural.products.in.the.past.year.secondary.education.or.more.ages.15',
      'Received.payments.for.agricultural.products.in.the.past.year.young.adults.ages.15.24',
      'Received.payments.for.agricultural.products.into.an.account.at.a.financial.institution.recipients.age.15',
      'Received.payments.for.agricultural.products.through.a.mobile.phone.recipients.age.15',
      'Received.wages.employed.in.public.sector.wage.recipients.age.15',
      'Received.wages.in.cash.wage.recipients.age.15',
      'Received.wages.in.the.past.year.age.15',
      'Received.wages.in.the.past.year.female.age.15',
      'Received.wages.in.the.past.year.income.poorest.40.ages.15',
      'Received.wages.in.the.past.year.income.richest.60.ages.15',
      'Received.wages.in.the.past.year.male.age.15',
      'Received.wages.in.the.past.year.older.adults.ages.25',
      'Received.wages.in.the.past.year.primary.education.or.less.ages.15',
      'Received.wages.in.the.past.year.rural.age.15',
      'Received.wages.in.the.past.year.secondary.education.or.more.ages.15',
      'Received.wages.in.the.past.year.young.adults.ages.15.24',
      'Received.wages.into.an.account.at.a.financial.institution.wage.recipients.age.15',
      'Received.wages.into.a.new.and.first.account.cashless.wage.recipients.age.15',
      'Received.wages.into.a.new.but.not.first.account.cashless.wage.recipients.age.15',
      'Received.wages.into.a.pre.existing.account.cashless.wage.recipients.age.15',
      'Received.wages.through.a.mobile.phone.wage.recipients.age.15',
      'Received.wages.withdraw.all.right.away.cashless.wage.recipients.age.15',
      'Received.wages.withdraw.over.time.as.needed.cashless.wage.recipients.age.15',
      'Saved.any.money.in.the.past.year.age.15',
      'Saved.any.money.in.the.past.year.female.age.15',
      'Saved.any.money.in.the.past.year.income.poorest.40.ages.15',
      'Saved.any.money.in.the.past.year.income.richest.60.ages.15',
      'Saved.any.money.in.the.past.year.male.age.15',
      'Saved.any.money.in.the.past.year.older.adults.ages.25',
      'Saved.any.money.in.the.past.year.primary.education.or.less.ages.15',
      'Saved.any.money.in.the.past.year.rural.age.15',
      'Saved.any.money.in.the.past.year.secondary.education.or.more.ages.15',
      'Saved.any.money.in.the.past.year.young.adults.ages.15.24',
      'Saved.at.a.financial.institution.age.15',
      'Saved.at.a.financial.institution.female.age.15',
      'Saved.at.a.financial.institution.income.poorest.40.ages.15',
      'Saved.at.a.financial.institution.income.richest.60.ages.15',
      'Saved.at.a.financial.institution.male.age.15',
      'Saved.at.a.financial.institution.older.adults.ages.25',
      'Saved.at.a.financial.institution.primary.education.or.less.ages.15',
      'Saved.at.a.financial.institution.rural.age.15',
      'Saved.at.a.financial.institution.secondary.education.or.more.ages.15',
      'Saved.at.a.financial.institution.young.adults.ages.15.24',
      'Saved.for.education.or.school.fees.age.15',
      'Saved.for.education.or.school.fees.female.age.15',
      'Saved.for.education.or.school.fees.income.poorest.40.ages.15',
      'Saved.for.education.or.school.fees.income.richest.60.ages.15',
      'Saved.for.education.or.school.fees.male.age.15',
      'Saved.for.education.or.school.fees.older.adults.ages.25',
      'Saved.for.education.or.school.fees.primary.education.or.less.ages.15',
      'Saved.for.education.or.school.fees.rural.age.15',
      'Saved.for.education.or.school.fees.secondary.education.or.more.ages.15',
      'Saved.for.education.or.school.fees.young.adults.ages.15.24',
      'Saved.for.old.age.age.15',
      'Saved.for.old.age.female.age.15',
      'Saved.for.old.age.income.poorest.40.ages.15',
      'Saved.for.old.age.income.richest.60.ages.15',
      'Saved.for.old.age.male.age.15',
      'Saved.for.old.age.older.adults.ages.25',
      'Saved.for.old.age.primary.education.or.less.ages.15',
      'Saved.for.old.age.rural.age.15',
      'Saved.for.old.age.secondary.education.or.more.ages.15',
      'Saved.for.old.age.young.adults.ages.15.24',
      'Saved.to.start.operate.or.expand.a.farm.or.business.age.15',
      'Saved.to.start.operate.or.expand.a.farm.or.business.female.age.15',
      'Saved.to.start.operate.or.expand.a.farm.or.business.income.poorest.40.ages.15',
      'Saved.to.start.operate.or.expand.a.farm.or.business.income.richest.60.ages.15',
      'Saved.to.start.operate.or.expand.a.farm.or.business.male.age.15',
      'Saved.to.start.operate.or.expand.a.farm.or.business.older.adults.ages.25',
      'Saved.to.start.operate.or.expand.a.farm.or.business.primary.education.or.less.ages.15',
      'Saved.to.start.operate.or.expand.a.farm.or.business.rural.age.15',
      'Saved.to.start.operate.or.expand.a.farm.or.business.secondary.education.or.more.ages.15',
      'Saved.to.start.operate.or.expand.a.farm.or.business.young.adults.ages.15.24',
      'Saved.using.a.savings.club.or.a.person.outside.the.family.age.15',
      'Saved.using.a.savings.club.or.a.person.outside.the.family.female.age.15',
      'Saved.using.a.savings.club.or.a.person.outside.the.family.income.poorest.40.ages.15',
      'Saved.using.a.savings.club.or.a.person.outside.the.family.income.richest.60.ages.15',
      'Saved.using.a.savings.club.or.a.person.outside.the.family.male.age.15',
      'Saved.using.a.savings.club.or.a.person.outside.the.family.older.adults.ages.25',
      'Saved.using.a.savings.club.or.a.person.outside.the.family.primary.education.or.less.ages.15',
      'Saved.using.a.savings.club.or.a.person.outside.the.family.rural.age.15',
      'Saved.using.a.savings.club.or.a.person.outside.the.family.secondary.education.or.more.ages.15',
      'Saved.using.a.savings.club.or.a.person.outside.the.family.young.adults.ages.15.24',
      'Sent.domestic.remittances.in.person.and.in.cash.senders.age.15',
      'Sent.domestic.remittances.in.the.past.year.age.15',
      'Sent.domestic.remittances.in.the.past.year.female.age.15',
      'Sent.domestic.remittances.in.the.past.year.income.poorest.40.ages.15',
      'Sent.domestic.remittances.in.the.past.year.income.richest.60.ages.15',
      'Sent.domestic.remittances.in.the.past.year.male.age.15',
      'Sent.domestic.remittances.in.the.past.year.older.adults.ages.25',
      'Sent.domestic.remittances.in.the.past.year.primary.education.or.less.ages.15',
      'Sent.domestic.remittances.in.the.past.year.rural.age.15',
      'Sent.domestic.remittances.in.the.past.year.secondary.education.or.more.ages.15',
      'Sent.domestic.remittances.in.the.past.year.young.adults.ages.15.24',
      'Sent.domestic.remittances.through.a.financial.institution.senders.age.15',
      'Sent.domestic.remittances.through.a.mobile.phone.senders.age.15',
      'Sent.domestic.remittances.through.a.money.transfer.operator.senders.age.15',
      'Used.a.mobile.phone.to.pay.for.school.fees.age.15',
      'Used.a.mobile.phone.to.pay.for.school.fees.female.age.15',
      'Used.a.mobile.phone.to.pay.for.school.fees.income.poorest.40.ages.15',
      'Used.a.mobile.phone.to.pay.for.school.fees.income.richest.60.ages.15',
      'Used.a.mobile.phone.to.pay.for.school.fees.male.age.15',
      'Used.a.mobile.phone.to.pay.for.school.fees.older.adults.ages.25',
      'Used.a.mobile.phone.to.pay.for.school.fees.primary.education.or.less.ages.15',
      'Used.a.mobile.phone.to.pay.for.school.fees.rural.age.15',
      'Used.a.mobile.phone.to.pay.for.school.fees.secondary.education.or.more.ages.15',
      'Used.a.mobile.phone.to.pay.for.school.fees.young.adults.ages.15.24',
      'Used.a.mobile.phone.to.pay.utility.bills.age.15',
      'Used.a.mobile.phone.to.pay.utility.bills.female.age.15',
      'Used.a.mobile.phone.to.pay.utility.bills.income.poorest.40.ages.15',
      'Used.a.mobile.phone.to.pay.utility.bills.income.richest.60.ages.15',
      'Used.a.mobile.phone.to.pay.utility.bills.male.age.15',
      'Used.a.mobile.phone.to.pay.utility.bills.older.adults.ages.25',
      'Used.a.mobile.phone.to.pay.utility.bills.primary.education.or.less.ages.15',
      'Used.a.mobile.phone.to.pay.utility.bills.rural.age.15',
      'Used.a.mobile.phone.to.pay.utility.bills.secondary.education.or.more.ages.15',
      'Used.a.mobile.phone.to.pay.utility.bills.young.adults.ages.15.24',
      'Used.an.account.at.a.financial.institution.to.pay.for.school.fees.age.15',
      'Used.an.account.at.a.financial.institution.to.pay.for.school.fees.female.age.15',
      'Used.an.account.at.a.financial.institution.to.pay.for.school.fees.income.poorest.40.ages.15',
      'Used.an.account.at.a.financial.institution.to.pay.for.school.fees.income.richest.60.ages.15',
      'Used.an.account.at.a.financial.institution.to.pay.for.school.fees.male.age.15',
      'Used.an.account.at.a.financial.institution.to.pay.for.school.fees.older.adults.ages.25',
      'Used.an.account.at.a.financial.institution.to.pay.for.school.fees.primary.education.or.less.ages.15',
      'Used.an.account.at.a.financial.institution.to.pay.for.school.fees.rural.age.15',
      'Used.an.account.at.a.financial.institution.to.pay.for.school.fees.secondary.education.or.more.ages.15',
      'Used.an.account.at.a.financial.institution.to.pay.for.school.fees.young.adults.ages.15.24',
      'Used.an.account.at.a.financial.institution.to.pay.utility.bills.age.15',
      'Used.an.account.at.a.financial.institution.to.pay.utility.bills.female.age.15',
      'Used.an.account.at.a.financial.institution.to.pay.utility.bills.income.poorest.40.ages.15',
      'Used.an.account.at.a.financial.institution.to.pay.utility.bills.income.richest.60.ages.15',
      'Used.an.account.at.a.financial.institution.to.pay.utility.bills.male.age.15',
      'Used.an.account.at.a.financial.institution.to.pay.utility.bills.older.adults.ages.25',
      'Used.an.account.at.a.financial.institution.to.pay.utility.bills.primary.education.or.less.ages.15',
      'Used.an.account.at.a.financial.institution.to.pay.utility.bills.rural.age.15',
      'Used.an.account.at.a.financial.institution.to.pay.utility.bills.secondary.education.or.more.ages.15',
      'Used.an.account.at.a.financial.institution.to.pay.utility.bills.young.adults.ages.15.24',
      'Used.an.account.to.make.a.transaction.through.a.mobile.phone.age.15',
      'Used.an.account.to.make.a.transaction.through.a.mobile.phone.female.age.15',
      'Used.an.account.to.make.a.transaction.through.a.mobile.phone.income.poorest.40.ages.15',
      'Used.an.account.to.make.a.transaction.through.a.mobile.phone.income.richest.60.ages.15',
      'Used.an.account.to.make.a.transaction.through.a.mobile.phone.male.age.15',
      'Used.an.account.to.make.a.transaction.through.a.mobile.phone.older.adults.ages.25',
      'Used.an.account.to.make.a.transaction.through.a.mobile.phone.primary.education.or.less.ages.15',
      'Used.an.account.to.make.a.transaction.through.a.mobile.phone.rural.age.15',
      'Used.an.account.to.make.a.transaction.through.a.mobile.phone.secondary.education.or.more.ages.15',
      'Used.an.account.to.make.a.transaction.through.a.mobile.phone.young.adults.ages.15.24',
      'Used.an.account.to.receive.government.transfers.age.15',
      'Used.an.account.to.receive.government.transfers.female.age.15',
      'Used.an.account.to.receive.government.transfers.income.poorest.40.ages.15',
      'Used.an.account.to.receive.government.transfers.income.richest.60.ages.15',
      'Used.an.account.to.receive.government.transfers.male.age.15',
      'Used.an.account.to.receive.government.transfers.older.adults.ages.25',
      'Used.an.account.to.receive.government.transfers.primary.education.or.less.ages.15',
      'Used.an.account.to.receive.government.transfers.rural.age.15',
      'Used.an.account.to.receive.government.transfers.secondary.education.or.more.ages.15',
      'Used.an.account.to.receive.government.transfers.young.adults.ages.15.24',
      'Used.an.account.to.receive.wages.age.15',
      'Used.an.account.to.receive.wages.female.age.15',
      'Used.an.account.to.receive.wages.income.poorest.40.ages.15',
      'Used.an.account.to.receive.wages.income.richest.60.ages.15',
      'Used.an.account.to.receive.wages.male.age.15',
      'Used.an.account.to.receive.wages.older.adults.ages.25',
      'Used.an.account.to.receive.wages.primary.education.or.less.ages.15',
      'Used.an.account.to.receive.wages.rural.age.15',
      'Used.an.account.to.receive.wages.secondary.education.or.more.ages.15',
      'Used.an.account.to.receive.wages.young.adults.ages.15.24',
      'Used.the.Internet.to.pay.bills.or.buy.things.age.15',
      'Used.the.Internet.to.pay.bills.or.buy.things.female.age.15',
      'Used.the.Internet.to.pay.bills.or.buy.things.income.poorest.40.ages.15',
      'Used.the.Internet.to.pay.bills.or.buy.things.income.richest.60.ages.15',
      'Used.the.Internet.to.pay.bills.or.buy.things.male.age.15',
      'Used.the.Internet.to.pay.bills.or.buy.things.older.adults.ages.25',
      'Used.the.Internet.to.pay.bills.or.buy.things.primary.education.or.less.ages.15',
      'Used.the.Internet.to.pay.bills.or.buy.things.rural.age.15',
      'Used.the.Internet.to.pay.bills.or.buy.things.secondary.education.or.more.ages.15',
      'Used.the.Internet.to.pay.bills.or.buy.things.young.adults.ages.15.24',
      'Withdrawal.in.the.past.year.with.an.account.age.15',
      'Withdrawals.in.a.typical.month.0.with.an.account.age.15',
      'Withdrawals.in.a.typical.month.1.or.2.with.an.account.age.15',
      'Withdrawals.in.a.typical.month.3.with.an.account.age.15')

length(x) == length(colnames(findex))

colnames(findex) <- x


# this list should be in every file to clean the country names
require(stringr)
findex$Country.Name <-str_trim(findex$Country.Name)
findex$Country.Name[findex$Country.Name == "Afghanistan, I.R. of"] <- "Afghanistan"
findex$Country.Name[findex$Country.Name == "Azerbaijan, Rep. of"] <- "Azerbaijan"
findex$Country.Name[findex$Country.Name == "Bahrain, Kingdom of"] <- "Bahrain"
findex$Country.Name[findex$Country.Name == "Bosnia & Herzegovina"] <- "Bosnia and Herzegovina"
findex$Country.Name[findex$Country.Name == "Cabo Verde"] <- "Cape Verde"
findex$Country.Name[findex$Country.Name == "Central African Republic"] <- "Central African Rep."
findex$Country.Name[findex$Country.Name == "Congo, Democratic Republic of"] <- "Congo, Dem. Rep."
findex$Country.Name[findex$Country.Name == "Congo, Dem. Rep. of"] <- "Congo, Dem. Rep."
findex$Country.Name[findex$Country.Name == "China,P.R.: Mainland"] <- "China"
findex$Country.Name[findex$Country.Name == "China,P.R.:Hong Kong"] <- "Hong Kong SAR, China"
findex$Country.Name[findex$Country.Name == "China,P.R.:Macao"] <- "Macao SAR, China"
findex$Country.Name[findex$Country.Name == "Congo, Republic of"] <- "Congo, Rep."
findex$Country.Name[findex$Country.Name == "Cote D'Ivoire"] <- "Cote d'Ivoire"
findex$Country.Name[findex$Country.Name == "Cote D&#39;Ivoire"] <- "Cote d'Ivoire"
findex$Country.Name[findex$Country.Name == "C√¥te d'Ivoire"] <- "Cote d'Ivoire"
findex$Country.Name[findex$Country.Name == "Cura√ßao"] <- "Curacao"
findex$Country.Name[findex$Country.Name == "Egypt, Arab Republic of"] <- "Egypt, Arab Rep."
findex$Country.Name[findex$Country.Name == "Egypt"] <- "Egypt, Arab Rep."
findex$Country.Name[findex$Country.Name == "Faroe Islands"] <- "Faeroe Islands"
findex$Country.Name[findex$Country.Name == "Iran, Islamic Republic of"] <- "Iran, Islamic Rep."
findex$Country.Name[findex$Country.Name == "Iran, I.R. of"] <- "Iran, Islamic Rep."
findex$Country.Name[findex$Country.Name == "Korea, Republic of"] <- "Korea, Rep."
findex$Country.Name[findex$Country.Name == "Lao People's Democratic Republic"] <- "Lao PDR"
findex$Country.Name[findex$Country.Name == "Lao People&#39;s Democratic Republic"] <- "Lao PDR"
findex$Country.Name[findex$Country.Name == "Lao People's Dem.Rep"] <- "Lao PDR"
findex$Country.Name[findex$Country.Name == "Macedonia, Former Yugoslav Republic of"] <- "Macedonia, FYR"
findex$Country.Name[findex$Country.Name == "Marshall Islands"] <- "Marshall Islands"
findex$Country.Name[findex$Country.Name == "Marshall Islands,Rep"] <- "Marshall Islands"
findex$Country.Name[findex$Country.Name == "Marshall Islands, Rep."] <- "Marshall Islands"
findex$Country.Name[findex$Country.Name == "Micronesia, Fed.Sts."] <- "Micronesia, Fed. Sts."
findex$Country.Name[findex$Country.Name == "São Tomé and Principe"] <- "Sao Tome and Principe"
findex$Country.Name[findex$Country.Name == "S√£o Tom√© and Principe"] <- "Sao Tome and Principe"
findex$Country.Name[findex$Country.Name == "S√£o Tom√© & Pr√≠ncipe"] <- "Sao Tome and Principe"
findex$Country.Name[findex$Country.Name == "Venezuela, Republica Bolivariana de"] <- "Venezuela, RB"
findex$Country.Name[findex$Country.Name == "Yemen, Republic of"] <- "Yemen, Rep."
findex$Country.Name[findex$Country.Name == "Yemen"] <- "Yemen, Rep."
findex$Country.Name[findex$Country.Name == "Slovakia"] <- "Slovak Republic"
findex$Country.Name[findex$Country.Name == "Congo Republic"] <- "Congo, Dem. Rep."
findex$Country.Name[findex$Country.Name == "Saint Lucia"] <- "St. Lucia"
findex$Country.Name[findex$Country.Name == "St. Vincent & Grens."] <- "St. Vincent and the Grenadines"
findex$Country.Name[findex$Country.Name == "Serbia, Republic of"] <- "Serbia"
findex$Country.Name[findex$Country.Name == "Timor Leste"] <- "Timor-Leste"
findex$Country.Name[findex$Country.Name == "Venezuela, Rep. Bol."] <- "Venezuela"
findex$Country.Name[findex$Country.Name == "Venezuela, Republica Bolivariana de"] <- "Venezuela"
findex$Country.Name[findex$Country.Name == "South Sudan, Rep. of"] <- "South Sudan"
findex$Country.Name[findex$Country.Name == "Anguilla"] <- "Anguila"
findex$Country.Name[findex$Country.Name == "Brunei Darussalam"] <- "Brunei"

#this was Serbia and Motenegro, changed to just Serbia (they are the same Income group)
findex$Country.Name[findex$Country.Name == "Serbia and Montenegro"] <- "Serbia"

#adding country code
countries <- read.csv('Clean.data/Country.List/CountryList.csv')
findex$Country.Code <- NULL
findex <- left_join(findex, countries, 'Country.Name')


write.csv(findex, file = 'Clean.data/findex.csv')